GET http://localhost:3001/movies/5ba1165e2e8a2a566bbc20fa
Accept: application/json

###
DELETE http://localhost:3001/movies/5ba1165e2e8a2a566bbc20fa
Accept: application/json

###
PUT http://localhost:3001/movies/5ba1165e2e8a2a566bbc20fa
Accept: application/json

###