POST http://{{baseUrl}}/users/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "username": "Andrzej",
  "password": "huj",
  "firstName": "dan",
  "lastName": "mark",
  "email": "wez@kurwa.pl"
}

###
GET http://localhost:3001/users/Janek
Accept: application/json
Authorization: Bearer {{authToken}}

###


